version: '3.8'

services:

  node-app: 
    build: .
    image: nodejs
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - network

  mongo:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    ports: 
      - 27017:27017
    networks:
      - network

networks:
  network:
    